### PR TITLE
Updated with Table filteration

### PR DESCRIPTION
**Pull request by mukilan2815**
Now user can easily filter and search with their requirements.
GSSOC'24

image

ISSUE CLOSED - #25

### CODE REVIEW

**Comment by Arghadip-Chatterjee** [comment]
@mukilan2815 Please Mention the Issue Number in Your PR Request. After That, I will Merge it. Without Mentioning the Issue Number I Cannot Merge it.

**Comment by mukilan2815** [comment]
updated the comment , please check it out and close it under GSSOC'24

**Comment by sethshivam11** [comment]
@mukilan2815 Sorry, but this is looking complex for the users (as users are very naive).

**Comment by mukilan2815** [comment]
Having filter options can be very helpful right

**Pull request closed without merging**
