### PR TITLE
Readme file is corrected and irregularities are removed

### PR DESCRIPTION
**Pull request by anijit18**
Fixes Issue  #91
Updated README.md file.

Updated the TechStack sention of the Readme file, made the punctuations regular.

Also rearranged the order: 1)Frontend 2)Backend 3)Database 4)Full Stack Integration

@sethshivam11 Please review this for any changes and let me know if you have any other change.

### CODE REVIEW

**Comment by anijit18** [comment]
@sethshivam11 Kindly tell me how to remove this failed check

**Comment by sethshivam11** [comment]
@anijit18 actually it's not working fine, that's why it's giving an error.

**Comment by anijit18** [comment]
@sethshivam11 I only made the changes in the readme file and have not touched any code files. So how does the code break?

**Comment by sethshivam11** [comment]
@anijit18 it does not break by you, it is broken by one of our contributors and we are working to fix it.

**Comment by anijit18** [comment]
@sethshivam11 After you resolve the error, do I need to create a new PR for this issue?

**Comment by sethshivam11** [comment]
@anijit18 don't worry about it I'll merge that and you have to do nothing.

**Pull request merged**
