### PR TITLE
solved_issue_12

### PR DESCRIPTION
**Pull request by gopalepic**
Made the Landing page which have a good  description about the Camput space website and its features including the problems its solving 

Its have some Animations 

Screenshot 2024-06-07 145437

### CODE REVIEW

**Comment by gopalepic** [comment]
@sethshivam11  i hope you like the changes made by me , 

do let me  if anything you wanted to change in the landing page , I will do it for you

**Comment by sethshivam11** [comment]
@gopalepic Animations are good but it is looking very basic. Also fix the mobile navbar to go to available-rooms route.

**Comment by gopalepic** [comment]
@sethshivam11 what changes do you want in animations ,

**Comment by gopalepic** [comment]
@sethshivam11 mobile navbar routing issue is solve now !
Screenshot 2024-06-07 175857

**Comment by sethshivam11** [comment]
@gopalepic The webpage design looks very basic, I want you to do some research and then implement it. The landing page should look modern, interactive, informative and welcoming.

**Comment by gopalepic** [comment]
@sethshivam11  got you , soon coming up with modern changes

**Comment by Arghadip-Chatterjee** [comment]
Hey, @gopalepic I am the Mentor of this Project. For Modern Animations, You can use Framer Motion and Many UI Components like Acceternity UI, Shadcn UI and many Taiwind UI Components like Flowbite and Many More. Happy Coding !!

**Comment by gopalepic** [comment]
@Arghadip-Chatterjee thanks for  your suggestions 
 
I will go through them

**Comment by sethshivam11** [comment]
@gopalepic I am not forcing you to add animations, this much animation is great. I want you to focus on the design of the landing page.

**Comment by gopalepic** [comment]
@sethshivam11 thanks for the information 

I will share some designs soon 
Do let me know which one you like the most for your website

**Comment by gopalepic** [comment]
@sethshivam11  , Do let me know if you think there should more changes , 

after going through your whole website , I thought these changes will definitely make your website
attractive

**Comment by sethshivam11** [comment]
@gopalepic No, the landing page is looking very basic and boring, add some images and make it attractive. You can consider the GitHub copilot site, or you can search modern landing pages on Google and consider them as well.

**Comment by gopalepic** [comment]
@sethshivam11  , This time i will try my best to make it more attractive

**Comment by gopalepic** [comment]
@sethshivam11 can you share some samples , it would be easy for me to understand your perspective for your webstie

**Comment by gopalepic** [comment]
@sethshivam11  , i made some changes , 

These are not the final changes , 
I just wanted to know that do you like the changes ??

**Comment by sethshivam11** [comment]
@gopalepic You are just using an image and the text is lagging, this is not looking like a landing page.
image

**Comment by gopalepic** [comment]
@sethshivam11  , share some examples or sites so that I can refer them , I wanted to know what's in your brain about the landing page

**Comment by sethshivam11** [comment]
@gopalepic Some references are:
- https://pin.it/2RJL9dzYa
- https://pin.it/4H0we34Hh
- https://pin.it/tXsA5vQNJ
- https://pin.it/6AoPMTFGS

**Comment by gopalepic** [comment]
@sethshivam11 , i was not healty from past few , days 
lets restart the work

**Comment by sethshivam11** [comment]
@gopalepic It's ok, get well soon.

**Comment by sethshivam11** [comment]
@gopalepic you are working on it?

**Comment by gopalepic** [comment]
@sethshivam11 yes , will update u soon

**Comment by sethshivam11** [comment]
@gopalepic I don't think you are working on it.

**Pull request closed without merging**
