### PR TITLE
Want to Add Sign Up Page and want to write backend of Login And SignUp Page #48

### PR DESCRIPTION
**Pull request by nishant0708**
-ADDED SIGNUP PAGE
-Updated Signup route logic 
#48 

https://github.com/sethshivam11/campus-space/assets/101548649/caa1a177-fce4-41b3-931c-7aaff7979dae

### CODE REVIEW

**Comment by sethshivam11** [comment]
@nishant0708 We don't want a signup page because only admins have to add data and teachers can book rooms. If any new teacher came he can get himself registered by contacting the admin.

**Comment by nishant0708** [comment]
So @sethshivam11 should I remove sign up page and raise pr again ? Because previously login was also not working

**Comment by sethshivam11** [comment]
@nishant0708 I don't know why but it's working in my side.

**Comment by nishant0708** [comment]
Okay then no issues 🥲🥲 @sethshivam11

**Pull request closed without merging**
