### PR TITLE
Updated the twitter icon

### PR DESCRIPTION
**Pull request by pani2004**
Solved issue #39  Screenshot (46)

### CODE REVIEW

**Comment by pani2004** [comment]
@Arghadip-Chatterjee @sethshivam11 Pls review the PR!!

**Comment by Arghadip-Chatterjee** [comment]
Ok, @pani2004 I am Merging Your PR. Thanks !! Happy Coding !!

**Comment by sethshivam11** [comment]
@pani2004 I think you are using a module which is not in our dependencies. 
@Arghadip-Chatterjee Please check this PR.

**Comment by sethshivam11** [comment]
@pani2004 I don't think for a logo we need to add some module, Please do this using a Twitter logo svg file or element.

**Comment by pani2004** [comment]
@sethshivam11 But the lucide react library is already in use, the icon I have used is from the React Icons library

**Comment by sethshivam11** [comment]
@pani2004 You can find SVG for twitter icon on the internet. Just use that.

**Pull request merged**
