### PR TITLE
Updated the twitter icon

### PR DESCRIPTION
**Pull request by pani2004**
Solved Issue #39

### CODE REVIEW

**Comment by pani2004** [comment]
@Arghadip-Chatterjee @sethshivam11 Made the required changes , pls review it

**Comment by sethshivam11** [comment]
@pani2004 Just download a SVG icon of X logo and save it in the public folder and then use it. Adding a random link may break the image.

**Comment by pani2004** [comment]
Ok @sethshivam11

**Comment by pani2004** [comment]
@sethshivam11 check now

**Comment by pani2004** [comment]
@Arghadip-Chatterjee @sethshivam11 Pls review the PR!!!

**Comment by sethshivam11** [comment]
@pani2004 please remove react import because it is causing a typescript defined but not used error.

**Pull request merged**
